/** Public, pure-TypeScript CrossMath API. */
import { generatePuzzle } from './generator'
import { hasUniqueSolution, solvePuzzle } from './solver'
import type { CrossMathEngine } from './types'

export type {
	ArithmeticConfig,
	ArithmeticOperator,
	CellCoordinate,
	CrossMathCell,
	CrossMathCellKind,
	CrossMathEngine,
	CrossMathOperator,
	CalibrationProfileSummary,
	DailyMode,
	DifficultyAnalysis,
	DifficultyMetrics,
	DifficultyScoreRange,
	DifficultyTier,
	EndlessProgress,
	Equation,
	EquationCellCoordinates,
	EquationDirection,
	EqualsCell,
	GeneratedPuzzle,
	NumberAssignment,
	NumberCell,
	OperatorCell,
	Puzzle,
	PuzzleDefinition,
	PuzzleGenerationConfig,
	PuzzleGrid,
	PuzzleMetadata,
	PuzzleSolution,
	PuzzleStructureRequirements,
	PuzzleValidationOptions,
	PuzzleValidationResult,
	GenerationProfile,
	MultiplicationTable,
	ProfiledPuzzle,
	SolutionCountResult,
	SolverMetrics,
	SolverResult,
	SolverStatus,
} from './types'

export {
	DEFAULT_GENERATION_CONFIG,
	PuzzleGenerationError,
	generatePuzzle,
} from './generator'
export { countSolutions, hasUniqueSolution, solvePuzzle } from './solver'
export { analyzeDifficulty } from './difficulty'
export { calibrateDifficultyProfile, calibrateDifficultyProfiles } from './calibration'
export {
	DifficultyGenerationError,
	generateCampaignPuzzle,
	generateDailyPuzzle,
	generateEndlessPuzzle,
	generateMultiplicationTablePuzzle,
	generatePuzzleForProfile,
	getCampaignGenerationProfile,
	getDailyGenerationProfile,
	getDifficultyProfile,
	getEndlessGenerationProfile,
	getMultiplicationTableGenerationProfile,
} from './profiles'
export { validatePuzzle } from './validator'
export {
	auditBinaryCeiling,
	analyzeNumberBank,
	analyzeAdvancedNumberBank,
	analyzeExpressionPuzzle,
	analyzeHybridPuzzle,
	calibrateExperimentalTracks,
	compareAdvancedCandidates,
	countAdvancedSolutions,
	countHybridSolutions,
	countExpressionSolutions,
	deriveDailyTrackSeed,
	deriveNumberBank,
	deriveTrackSeed,
	DEFAULT_LONG_EXPRESSION_CONFIG,
	evaluateExpression,
	generateDailyTrackPuzzle,
	generateLongExpressionPuzzle,
	generateHybridPuzzle,
	generateTrackPuzzle,
	getTrackProfile,
	measureOccupiedDensity,
	renderExpressionPuzzleAscii,
	renderHybridPuzzleAscii,
	renderPuzzleAscii,
	solveExpressionPuzzle,
	validateExperimentalTrackPuzzle,
	deriveAdvancedNumberBank,
	buildPregeneratedCampaignCatalog,
	validatePregeneratedCampaignCatalog,
	serializePregeneratedCampaignCatalog,
	solveHybridPuzzle,
} from './experimental'
export type {
	BinaryCeilingAuditRow,
	ExperimentalDailyMode,
	ExperimentalGenerationOptions,
	ExperimentalTrack,
	ExperimentalTrackProfile,
	ExperimentalTrackPuzzle,
	ExperimentalCalibrationSummary,
	AdvancedCandidateKind,
	AdvancedCandidateSummary,
	AdvancedComparisonReport,
	AdvancedDifficultyAnalysis,
	AdvancedNumberBankPuzzle,
	CampaignCatalogOptions,
	CatalogValidationReport,
	GeneratedHybridPuzzle,
	HybridEquation,
	HybridGenerationConfig,
	HybridPuzzle,
	HybridSolutionCountResult,
	PregeneratedCampaignCatalog,
	PregeneratedCampaignEntry,
	ExpressionDirection,
	ExpressionEquation,
	ExpressionEvaluation,
	ExpressionPuzzle,
	ExpressionSolution,
	GeneratedExpressionPuzzle,
	LongExpressionGenerationConfig,
	NumberBank,
	NumberBankAnalysis,
	NumberBankItem,
	NumberBankMode,
	OccupiedDensityMetrics,
} from './experimental'
export { deriveSeed } from './rng'
export {
	evaluateArithmetic,
	isValueInRange,
	operatorSymbol,
} from './arithmetic'
export {
	coordinateKey,
	coordinatesEqual,
	getCell,
} from './model'

export function createCrossMathEngine(): CrossMathEngine {
	return {
		generate: generatePuzzle,
		solve: solvePuzzle,
		hasUniqueSolution,
	}
}
